name: CI and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Typecheck, Lint & Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Create CI environment file
        run: |
          cat > .env.local << EOF
          NEXTAUTH_SECRET=ci-secret-key-$(date +%s)
          NEXTAUTH_URL=http://localhost:3000
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_ci
          STRIPE_SECRET_KEY=sk_test_ci
          DATABASE_URL=file:./prisma/dev.db
          NODE_ENV=production
          CI=true
          EOF

      - name: Install deps (lockfile exact, skip scripts)
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci --ignore-scripts --legacy-peer-deps
          else
            echo "package-lock.json not found, using npm install"
            npm install --ignore-scripts --legacy-peer-deps
          fi

      - name: Install sharp for Linux
        run: |
          npm install --platform=linux --arch=x64 sharp
          npm rebuild sharp

      - name: Generate Prisma client (if applicable)
        run: |
          # Set environment to bypass certificate issues
          export NODE_TLS_REJECT_UNAUTHORIZED=0
          # Generate Prisma client with retry logic
          for i in {1..3}; do
            echo "Attempt $i to generate Prisma client..."
            if npx prisma generate; then
              echo "Prisma client generated successfully"
              break
            else
              echo "Attempt $i failed"
              if [ $i -eq 3 ]; then
                echo "All attempts failed. Exiting."
                exit 1
              fi
              sleep 2
            fi
          done
        env:
          DATABASE_URL: "file:./prisma/dev.db"
          NEXTAUTH_SECRET: "ci-secret-key"
          NEXTAUTH_URL: "http://localhost:3000"

      - name: Type check
        run: npm run type-check:ci
        env:
          NEXTAUTH_SECRET: "ci-secret-key"
          NEXTAUTH_URL: "http://localhost:3000"

      - name: Lint
        run: npm run lint
        env:
          NEXTAUTH_SECRET: "ci-secret-key"
          NEXTAUTH_URL: "http://localhost:3000"

      - name: Build
        run: npm run build
        env:
          NEXTAUTH_SECRET: "ci-secret-key"
          NEXTAUTH_URL: "http://localhost:3000"
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_ci"
          STRIPE_SECRET_KEY: "sk_test_ci"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: next-build
          path: |
            .next
            package.json
            package-lock.json
            next.config.js
            public
