name: CI and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Type check (CI-safe)
        run: npm run type-check:ci

      - name: Lint (no warnings allowed)
        run: npm run lint:ci

      - name: Unit tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Size budget check
        run: npm run size-limit

  deploy:
    needs: ci
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build for deployment
        run: npm run build

      - name: Create .env.production for runtime
        run: |
          {
            echo "NODE_ENV=production"
            echo "NEXTAUTH_URL=http://localhost:3000"
            echo "NEXTAUTH_SECRET=ci-test-secret-key-for-github-actions-2024-long-enough-for-validation"
            echo "DATABASE_URL=file:./ci-test.db"
            echo "NEXT_PUBLIC_SITE_URL=http://localhost:3000"
            echo "GOOGLE_CLIENT_ID="
            echo "GOOGLE_CLIENT_SECRET="
            echo "TURNSTILE_SECRET_KEY="
            echo "RATE_LIMIT_WINDOW_MS=900000"
            echo "LOGIN_MAX_FAILS=5"
          } > .env.production

      - name: Start standalone server on :3000 (background)
        run: |
          nohup node .next/standalone/server.js -p 3000 > server.log 2>&1 & echo $! > server.pid
          sleep 10

      - name: Smoke test (/, /api/healthz)
        run: |
          npx wait-on -t 60000 http://localhost:3000/
          curl -f http://localhost:3000/ || exit 1
          curl -f http://localhost:3000/api/healthz || exit 1

      - name: Tail server log on failure
        if: failure()
        run: tail -n 200 server.log || true

      - name: Stop server
        if: always()
        run: kill "$(cat server.pid)" || true

      - name: Export artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
            package.json
            package-lock.json
            next.config.js
            public

      # Vercel deployment will be added when ready for production
