name: CI and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Typecheck, Lint & Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (lockfile exact, skip scripts)
        run: npm ci --ignore-scripts --legacy-peer-deps

      - name: Generate Prisma client (if applicable)
        run: npx prisma generate
        continue-on-error: true

      - name: Type check
        run: npm run type-check:ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: next-build
          path: |
            .next
            package.json
            package-lock.json
            next.config.js
            public
