name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Setup test environment
        run: |
          echo "DATABASE_URL=file:./test.db" >> $GITHUB_ENV
          echo "NEXTAUTH_URL=http://localhost:3000" >> $GITHUB_ENV
          echo "NEXTAUTH_SECRET=test-secret-key" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=sk_test_123" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_test_123" >> $GITHUB_ENV

      - name: Run linting
        run: npm run lint
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-key
          STRIPE_SECRET_KEY: sk_test_123
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_123

      - name: Build application
        run: npm run build:no-typescript
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-key
          STRIPE_SECRET_KEY: sk_test_123
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_123

      - name: Run tests
        run: npm run test:ci
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-key
          STRIPE_SECRET_KEY: sk_test_123
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_123

      - name: Run Web Vitals check
        run: npm run web-vitals-check
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-key
          STRIPE_SECRET_KEY: sk_test_123
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_123
