name: Error Monitoring & Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: error-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Typecheck, Lint & Quality Gates
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      CI: "true"
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (lockfile exact, skip scripts)
        run: npm ci --ignore-scripts --legacy-peer-deps

      # Ensure sharp is properly installed with platform-specific binaries
      - name: Install sharp with optional dependencies
        run: npm install --include=optional sharp

      # Prisma is optional; keep non-fatal if not used
      - name: Generate Prisma client (if applicable)
        run: npx prisma generate
        continue-on-error: true

      - name: Type check
        run: npm run type-check:ci

      - name: Lint
        run: npm run lint

      # Build surfaces many runtime/syntax errors early
      - name: Build
        run: npm run build

      # Optional quality checks (non-blocking at first)
      - name: Web Vitals Guard (non-blocking)
        run: npm run web-vitals-check
        continue-on-error: true

      - name: Bundle Size Check (non-blocking)
        run: npm run size-limit
        continue-on-error: true
