name: Performance & Bundle Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: perf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perf:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Type check (CI-safe)
        run: npm run type-check:ci

      - name: Lint (no warnings allowed)
        run: npm run lint:ci

      - name: Unit tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Size budget check
        run: npm run size-limit

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start server on :3000 (background)
        run: |
          nohup node .next/standalone/server.js -p 3000 -H 127.0.0.1 > server.log 2>&1 & echo $! > server.pid
          sleep 5

      - name: Lighthouse (performance only)
        run: |
          npx wait-on -t 60000 http://localhost:3000/
          npx lighthouse http://localhost:3000/ --only-categories=performance --output json --output html --output-path ./lighthouse-report

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-reports
          path: |
            lighthouse-report.json
            lighthouse-report.html
            server.log

      - name: Stop server
        if: always()
        run: kill "$(cat server.pid)" || true
