name: Performance & Bundle Analysis

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  perf:
    name: Lighthouse (local) — non-blocking
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: "file:./dev.db"

      - name: Verify Prisma client generation
        run: |
          npm run debug:prisma

      - name: Build
        run: npm run build

      - name: Start server
        run: |
          # Next.js builds to .next directory, not out
          if [ -d ".next" ]; then
            # Start Next.js server
            nohup npx next start >/dev/null 2>&1 &
          else
            # Fallback to serve if static export exists
            nohup npx serve -s out >/dev/null 2>&1 &
          fi

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Lighthouse (homepage)
        run: |
          npx -y @lhci/cli@0.12.0 collect --url=http://localhost:3000/ --outputPath=./lighthouse-report.json || true
          npx -y @lhci/cli@0.12.0 upload --target=filesystem --outputDir=./ || true
        env:
          CHROME_PATH: google-chrome-stable

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-report
          path: |
            ./lighthouse-report.json
