name: Performance & Bundle Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: perf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perf:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Type check (CI-safe)
        run: npm run type-check:ci

      - name: Lint (no warnings allowed)
        run: npm run lint:ci

      - name: Unit tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Size budget check
        run: npm run size-limit

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Create .env.test for runtime
        run: |
          {
            echo "NODE_ENV=test"
            echo "NEXTAUTH_URL=http://localhost:3000"
            echo "NEXTAUTH_SECRET=ci-test-secret-key-for-github-actions-2024-long-enough-for-validation"
            echo "DATABASE_URL=file:./test.db"
            echo "NEXT_PUBLIC_SITE_URL=http://localhost:3000"
            echo "GOOGLE_CLIENT_ID="
            echo "GOOGLE_CLIENT_SECRET="
            echo "TURNSTILE_SECRET_KEY="
            echo "RATE_LIMIT_WINDOW_MS=900000"
            echo "LOGIN_MAX_FAILS=5"
          } > .env.test

      - name: Start server on :3000 (background)
        run: |
          nohup node .next/standalone/server.js -p 3000 -H 127.0.0.1 > server.log 2>&1 & echo $! > server.pid
          sleep 10
          curl -f http://localhost:3000/ || (echo "Server failed to start" && cat server.log && exit 1)

      - name: Lighthouse (performance only) - with fallback
        run: |
          npx wait-on -t 60000 http://localhost:3000/
          # Try with default Chrome first
          if npx lighthouse http://localhost:3000/ --only-categories=performance --output json --output html --output-path ./lighthouse-report --chrome-flags="--headless --no-sandbox --disable-gpu"; then
            echo "Lighthouse completed successfully"
          else
            echo "Lighthouse failed with default Chrome, trying with Playwright Chromium"
            # Use Playwright Chromium as fallback
            CHROME_PATH=/home/ubuntu/.cache/ms-playwright/chromium-*/chrome-linux/chrome npx lighthouse http://localhost:3000/ --only-categories=performance --output json --output html --output-path ./lighthouse-report --chrome-flags="--headless --no-sandbox --disable-gpu" || echo "Lighthouse failed, but continuing..."
          fi

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-reports
          path: |
            lighthouse-report.json
            lighthouse-report.html
            server.log

      - name: Stop server
        if: always()
        run: kill "$(cat server.pid)" || true