name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Setup env
        run: |
          cp .env.example .env.test || true
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.test
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/testdb" >> .env.test
          echo "STRIPE_SECRET_KEY=sk_test_123" >> .env.test
          echo "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_test_123" >> .env.test

      - name: Prepare DB
        run: |
          npx prisma migrate deploy
          npx prisma db seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Cypress binary
        run: npx cypress install

      - name: Cache Playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Run unit tests
        run: npm run test:ci

      - name: Build and start app
        run: |
          npm run build
          npm run start &
          npx wait-on http://localhost:3000

      - name: Run E2E tests
        run: npm run cypress:run

      - name: Run Lighthouse
        run: npm run test:lighthouse

      - name: Upload coverage
        uses: codecov/codecov-action@v4
