name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-and-types:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Type check (CI-safe)
        run: npm run type-check:ci

      - name: Lint (no warnings allowed)
        run: npm run lint:ci

      - name: Unit tests
        run: npm run test:ci
