name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install --no-audit --no-fund --legacy-peer-deps
          echo "Dependencies installed successfully"
          npm list --depth=0
          echo "Running postinstall script..."
          npm run postinstall

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Setup test environment
        run: |
          echo "DATABASE_URL=file:./test.db" >> $GITHUB_ENV
          echo "NEXTAUTH_URL=http://localhost:3000" >> $GITHUB_ENV
          echo "NEXTAUTH_SECRET=test-secret-key" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=sk_test_123" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_test_123" >> $GITHUB_ENV
          echo "SKIP_TYPE_CHECK=true" >> $GITHUB_ENV
          echo "NEXT_SKIP_TYPE_CHECK=true" >> $GITHUB_ENV

      - name: Run tests
        run: npm run test:ci
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-key
          STRIPE_SECRET_KEY: sk_test_123
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_123
          SKIP_TYPE_CHECK: true
          NEXT_SKIP_TYPE_CHECK: true

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-key
          STRIPE_SECRET_KEY: sk_test_123
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_123
          SKIP_TYPE_CHECK: true
          NEXT_SKIP_TYPE_CHECK: true

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret-key
          STRIPE_SECRET_KEY: sk_test_123
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: pk_test_123
          SKIP_TYPE_CHECK: true
          NEXT_SKIP_TYPE_CHECK: true
