name: UI PR Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ui-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_ENV: test
      CI: true
      BASE_URL: http://localhost:3000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Type check (CI-safe)
        run: npm run type-check:ci

      - name: Lint (no warnings allowed)
        run: npm run lint:ci

      - name: Unit tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Install Playwright (with deps)
        run: npx playwright install --with-deps

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start server on :3000 (background)
        run: |
          nohup node .next/standalone/server.js -p 3000 > server.log 2>&1 & echo $! > server.pid
          sleep 5

      - name: Run Playwright tests
        run: npx playwright test --reporter=github --project=chromium
        env:
          BASE_URL: ${{ env.BASE_URL }}

      - name: Upload Playwright report (if generated)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Tail log on failure
        if: failure()
        run: tail -n 200 server.log || true

      - name: Stop server
        if: always()
        run: kill "$(cat server.pid)" || true
